modLoader="javafml"
loaderVersion="${loader_version_range}"
license="https://github.com/stlouisn/minecraft_rails/blob/1.20.1/LICENSE"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/stlouisn/minecraft_rails"
issueTrackerURL="https://github.com/stlouisn/minecraft_rails/issues"
logoFile="logo.png"
authors=${mod_authors}
credits=${mod_credits}
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"